require("globals")
print("-- Starting Loading the config at "..tostring(dt_now("time")))
require("classes.reload")():start()
with(Timer("Another operation"), function(t)
    require("_load")
    print("-- Time taken: "..t:format_elapsed())
end)
print("-- Reached the end of the config at "..tostring(dt_now("time")))
hs.alert.show("Config loaded")
